#!/bin/bash
# Basic script to purge multiple Oracle tables by batchs of rows
# Ex: 
#   $ . purge_oracle
#   $ echo "my_table where field1 = 'foo' and updated < sysdate - 7
#   other_table where field1 = 'bar' and updated < sysdate - 7" | purge_oracle

row_purged_per_iteration=2000

info(){ echo `date '+%Y-%m-%d %H:%M:%S'` [`basename $0`] "$@"; }

cd `dirname $0`

sql(){
  {
    sqlplus -S / as sysdba <<EOS
set head off
set pages 0 feed off
WHENEVER SQLERROR EXIT 5 ROLLBACK;
$@
exit;
EOS
  } 2>&1
}

purge_oracle(){
 while read request; do
  count=`sql "select count(*) from $request;"` || { info "$request KO: $count"; continue; }
  info "$count rows selected for request: $request"
  if test $count -gt 0; then
    nb_purge=`expr $count / $row_purged_per_iteration + 1`
    i=0; while test $i -lt $nb_purge; do i=`expr $i + 1`
      output=`sql "delete from $request and rownum < $row_purged_per_iteration;"`
      info "Purge $i out of $nb_purge $output"
    done
  fi
 done
}